apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-03-17T14:49:14Z"
  generation: 1
  labels:
    app: ylz-xyz-device-svc
  name: ylz-xyz-device-svc
  namespace: default
  resourceVersion: "278817"
  selfLink: /apis/apps/v1/namespaces/default/deployments/ylz-xyz-device-svc
  uid: 78a04eca-685e-11ea-b055-42010a9c00b1
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ylz-xyz-device-svc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ylz-xyz-device-svc
    spec:
      containers:
      - env:
        - name: API_PREFIX
          valueFrom:
            configMapKeyRef:
              key: API_PREFIX
              name: ylz-xyz-device-svc-config-ncgj
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              key: NODE_ENV
              name: ylz-xyz-device-svc-config-ncgj
        - name: PORT
          valueFrom:
            configMapKeyRef:
              key: PORT
              name: ylz-xyz-device-svc-config-ncgj
        - name: FIRESTORE_TYPE
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_TYPE
              name: ylz-xyz-device-svc-config-ncgj
        - name: FIRESTORE_PROJECT_ID
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_PROJECT_ID
              name: ylz-xyz-device-svc-config-ncgj
        - name: FIRESTORE_PRIVATE_KEY_ID
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_PRIVATE_KEY_ID
              name: ylz-xyz-device-svc-config-ncgj
        - name: FIRESTORE_PRIVATE_KEY
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_PRIVATE_KEY
              name: ylz-xyz-device-svc-config-ncgj
        - name: FIRESTORE_CLIENT_EMAIL
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_CLIENT_EMAIL
              name: ylz-xyz-device-svc-config-ncgj
        - name: FIRESTORE_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_CLIENT_ID
              name: ylz-xyz-device-svc-config-ncgj
        - name: FIRESTORE_AUTH_URI
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_AUTH_URI
              name: ylz-xyz-device-svc-config-ncgj
        - name: FIRESTORE_TOKEN_URI
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_TOKEN_URI
              name: ylz-xyz-device-svc-config-ncgj
        - name: FIRESTORE_AUTH_PROVIDER_X509_CERT_URL
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_AUTH_PROVIDER_X509_CERT_URL
              name: ylz-xyz-device-svc-config-ncgj
        - name: FIRESTORE_CLIENT_X509_CERT_URL
          valueFrom:
            configMapKeyRef:
              key: FIRESTORE_CLIENT_X509_CERT_URL
              name: ylz-xyz-device-svc-config-ncgj
        image: gcr.io/ylz-xyz-infra/github.com/aytekinyaliz/ylz-xyz-device-svc:17df7b4
        imagePullPolicy: IfNotPresent
        name: ylz-xyz-device-svc-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2020-03-17T14:49:24Z"
    lastUpdateTime: "2020-03-17T14:49:24Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-03-17T14:49:14Z"
    lastUpdateTime: "2020-03-17T14:49:24Z"
    message: ReplicaSet "ylz-xyz-device-svc-76dc49784" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3