apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-03-17T14:55:10Z"
  labels:
    app: ylz-xyz-device-svc
  name: ylz-xyz-device-svc-service
  namespace: default
  resourceVersion: "280540"
  selfLink: /api/v1/namespaces/default/services/ylz-xyz-device-svc-service
  uid: 4c7a6a9f-685f-11ea-b055-42010a9c00b1
spec:
  clusterIP: 10.0.31.90
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31406
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: ylz-xyz-device-svc
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.198.97.150
